ARG METADATASERVICE_BASE
ARG SEARCHSERVICE_BASE

FROM node:12-slim as node-stage
WORKDIR /app/amundsen_application/static

COPY amundsen/frontend/amundsen_application/static/package.json /app/amundsen_application/static/package.json
COPY amundsen/frontend/amundsen_application/static/package-lock.json /app/amundsen_application/static/package-lock.json
RUN npm install

COPY amundsen/frontend/amundsen_application/static/ /app/amundsen_application/static/

# CUSTOM CONFIGS

COPY frontend/static /usr/local/amundsen/frontend/configs/static

RUN npm rebuild node-sass
RUN npm run dev-build

COPY amundsen/frontend /app

FROM python:3.7-slim
WORKDIR /app

COPY amundsen/frontend /app
COPY amundsen/requirements-dev.txt /app/requirements-dev.txt
COPY amundsen/requirements-common.txt /app/requirements-common.txt

COPY --from=node-stage /app /app

RUN pip3 install -e .

ENTRYPOINT [ "python3" ]
CMD [ "amundsen_application/wsgi.py" ]
