FROM python:3.7-slim
WORKDIR /app
RUN pip3 install gunicorn

COPY amundsen/search/ /app/
COPY amundsen/requirements-dev.txt /app/requirements-dev.txt
COPY amundsen/requirements-common.txt /app/requirements-common.txt
RUN pip3 install -e .

CMD [ "python3", "search_service/search_wsgi.py" ]
